### ISSUE TITLE
open hashpack from page

### ISSUE THREAD

**Issue by JoseHerminioCollas** [JoseHerminioCollas/aaartoCanvas#7]
https://github.com/hashgraph/hedera-nft-minter/blob/main/src/utils/hooks/wallets/useHashPack.ts#L42

**Comment by JoseHerminioCollas** [comment]
how to convert NPM to browser script, browserify

**Comment by JoseHerminioCollas** [comment]
https://docs.hedera.com/hedera

**Comment by JoseHerminioCollas** [comment]
https://github.com/hashgraph/hedera-wallet-connect/blob/main/docs/docs/wallet-guide.md

**Comment by JoseHerminioCollas** [comment]
I want to make an opensea type of app. I am looking at hashconnect. Is hedera-wallet-connect an option? Do I use one or the other? Or do I use both?

**Comment by JoseHerminioCollas** [comment]
https://www.npmjs.com/package/hashconnect

**Comment by JoseHerminioCollas** [comment]
hello i am trying to use hashconnect v3
this is the repo:
https://github.com/JoseHerminioCollas/aaarto/tree/hashconnect-2
but i keep getting this errror:
`Uncaught TypeError: execOptions.factory.call is not a function
    at __webpack_require__ (index.js:11390:32)
    at fn (index.js:11654:21)
    at eval (axios.js:5:67)
    at ./node_modules/axios/lib/axios.js (index.js:7730:1)`

**Comment by JoseHerminioCollas** [comment]
https://github.com/hashgraph/hedera-sdk-js/blob/main/src/account/AccountId.js#L235
https://docs.metamask.io/wallet/connect/wallet-api/
